#####################################################################################
# Get reference data for the Matakana inventory project, calculate interactions
# These data are from the LPM plots
# Try to keep this generic if possible
# J.Dash Jan 2016
#####################################################################################

# Get reference lidar data
# This file was generated by LASTools using the lascanopy command and contains a one line entry for each plot
# The Plot_ID in the first column contains the plot name
ref.lid<-read.csv(paste(data.dir, 'ref_lidar.csv', sep=""))

#Get reference plot data
ref.stand.summary<-read.csv(paste(data.dir,'stand_summary.csv', sep="")) #This is the stand summary table from ytgen
#head(ref.stand.summary)
ref.stand.summary<-subset(ref.stand.summary, select=c(PlotName, Age, BasalArea, TopHeight, Stocking, TotalRecoverableVolume))
names(ref.stand.summary)[names(ref.stand.summary) == 'PlotName'] <- 'Plot_ID' #Rename the Plot_ID column


ref.log.grade<-read.csv(paste(data.dir, 'loggrade_pivot_lpm1.csv', sep="")) #This table contains a one line summary for each plot detailing the 
#log product volumes required for prediction
names(ref.log.grade)[names(ref.log.grade) == 'PlotName'] <- 'Plot_ID' #Rename the Plot_ID column
ref.log.grade<-subset(ref.log.grade, select=-c(PopulationName))

#ref.trees<-read.csv('lpm_alltrees_merged.csv') #This file contains a one line summary for each tree containing the field measurements
#ref.trees<-subset(ref.trees, ref.trees$HeightStatus=='NORMAL') #Get rid of non-normal height trees like broken tops

#Get the average height and dbh for each plot
#ref.mean.height<- ref.trees %>% group_by(PlotId) %>% summarise (mean_height=mean(Height, na.rm=T), mean_dbh=mean(DBH, na.rm=T))
#names(ref.mean.height)[names(ref.mean.height) == 'PlotId'] <- 'Plot_ID' #Rename the Plot_ID column

# merge the field plot data
ref.plots<-merge(ref.stand.summary, ref.log.grade, by='Plot_ID')
#ref.plots<-merge(ref.plots, ref.mean.height, by='Plot_ID')

# Complete the reference dataset by merging in the plot level lidar data
ref<-merge(ref.plots, ref.lid, by="Plot_ID")
#pairs(~mean_height+TopHeight+p99+p95+p50+p30, data=ref)
#pairs(~TotalRecoverableVolume+qav+dns+p50+p30+b70, data=ref)

# Get reference plot locations
ref.loc<-read.csv(paste(data.dir, 'plot_locations_final.csv', sep=""))
ref.loc<-ref.loc[with(ref.loc, order(Plot_ID)),]
coordinates(ref.loc)<-~X+Y
proj4string(ref.loc)<-proj4string
#writeOGR(ref.loc, dsn='D:\\MatakanaIsland\\final_analysis_yieldtables', layer ='ref', driver='ESRI Shapefile')

# Get the shape containing anciliary data
shp<-shapefile(paste(data.dir, 'Matakana 4 Scion_region.shp', sep = ""))
proj4string(shp)<-proj4string

# Plot it up for a check
plot(shp) ; plot(ref.loc, add=T, col='red', pch=21)
print("This figure shows the reference plots overlaid on the shape file containing the anciliary data")

# Extract anciliary data from shapefile 
ref.anc<-over(ref.loc, shp)
# This is not generic yet but it should
ref.anc<-subset(ref.anc, select=c(NZ_Site, Avg_Elev, Avg_Slp_De, Avg_Aspect, Cur_silvi_))

ref<-cbind(ref, ref.anc) # add to the reference dataset
# There may be an issue with NAs being brought into the anciliary data that needs to be fixed.


#************************
#Add local maxima and mean canopy width into the reference dataset
#***************************

#Load in the local maxima information
loc.max<-read.csv(paste(data.dir, 'treecounts_ip_.csv', sep = ""))
coordinates(loc.max)<-~X+Y
proj4string(loc.max)<-proj4string

#buffer ref.loc to use in over
ref.loc.buf<-gBuffer(ref.loc, width=14, byid=TRUE ,quadsegs = 50) #Width here is approximate to the plot radius
proj4string(ref.loc.buf)<-proj4string
#plot(ref.loc.buf)

# combine is.na() with over() to do the containment test; note that we
# need to "demote" ref.buf.loc to a SpatialPolygons object first
inside.plots <- !is.na(over(loc.max, as(ref.loc.buf, "SpatialPolygons")))

#This converts the buffered plot shapes to a spatial poly dataframe
ref.loc.buf.df <-SpatialPolygonsDataFrame(ref.loc.buf, data=as.data.frame(ref.loc))

#This will assign each tree to a plot 
loc.max$Plot_ID <- over(loc.max, ref.loc.buf.df)$Plot_ID
loc.max$Plot_ID<-as.factor(loc.max$Plot_ID)

#Turn tree locations into data frame for summary
loc.max.df<-as.data.frame(loc.max)
loc.max.df$Plot_ID<-as.factor(loc.max.df$Plot_ID)
#str(loc.max.df)

#Crate EABA summaries a single entry for each plot
loc.max.plot<- loc.max.df %>% group_by(Plot_ID) %>% summarise (p.count=length(Tree.no.), 
                                                               mean.cr.width=mean(Max.crown.width),
                                                               var.cr.width=var(Max.crown.width),
                                                               std.cr.width=sd(Max.crown.width),
                                                               min.cr.width=min(Max.crown.width),
                                                               max.cr.width=max(Max.crown.width),
                                                               mean.Ht.cr.base=mean(Ht.to.crown.base),
                                                               min.Ht.cr.base=min(Ht.to.crown.base),
                                                               max.Ht.cr.base=max(Ht.to.crown.base),
                                                               std.Ht.cr.base=sd(Ht.to.crown.base),
                                                               var.Ht.cr.base=var(Ht.to.crown.base),
                                                               mean.chm.ht=mean(Height),
                                                               min.chm.ht=min(Height),
                                                               max.chm.ht=max(Height),
                                                               std.chm.ht=sd(Height),
                                                               var.chm.ht=var(Height))

#Merge thes EABA characteristics into the ref dataset
ref<-merge(ref, loc.max.plot, by="Plot_ID")
ref$p.stocking<-ref$p.count/0.06

#plot(Stocking ~ p.count, data =ref)
#plot(Stocking ~ p.stocking, data =ref)
#sph.ref<-lm(Stocking ~ p.count, data = ref)
#summary(sph.ref)
# plot(TopHeight ~ chm.ht, data =ref)
# plot(P_Sawlog ~ min.cr.width, data=ref)
# plot(Pulp ~ max.cr.width, data=ref)
# plot(Pulp ~ std.cr.width, data=ref)
# abline(a=0, b=1)

###These lines are case specific and maybe should be removed eventually

ref$NZ_Site<-ifelse (ref$NZ_Site == 0, mean(ref$NZ_Site), ref$NZ_Site)
ref$Cur_silvi_<-ifelse(ref$Cur_silvi_ == 'na', "PRX1", ref$Cur_silvi_) #Work around for nowCHECK THESE
ref$Cur_silvi_<-as.factor(ref$Cur_silvi_) #This nreeds to be a factor for RF to work

#This value is just to stop failures associated with log 0 and sqrt 0
ref[ref==0]<-0.0000001

# Calculate interactions   #Check interations
ref<-subset(ref, select=-c(radius,  Plot_ID))

#Age interaction
ref$ag.avg <- ref$avg*ref$Age
ref$ag.kur <- ref$kur*ref$Age
ref$ag.p30 <- ref$p30*ref$Age
ref$ag.p95 <- ref$p95*ref$Age
ref$ag.b20 <- ref$b20*ref$Age
ref$ag.b90 <- ref$b90*ref$Age
ref$ag.c01 <- ref$c01*ref$Age
ref$ag.c05 <- ref$c05*ref$Age
ref$ag.dns <- ref$dns*ref$Age
ref$ag.Avg_Aspect <- ref$Avg_Aspect*ref$Age
ref$ag.var.cr.width <- ref$var.cr.width*ref$Age
ref$ag.mean.Ht.cr.base <- ref$mean.Ht.cr.base*ref$Age
ref$ag.var.Ht.cr.base <- ref$var.Ht.cr.base*ref$Age
ref$ag.std.chm.ht <- ref$std.chm.ht*ref$Age
ref$ag.Age <- ref$Age*ref$Age
ref$ag.qav <- ref$qav*ref$Age
ref$ag.p05 <- ref$p05*ref$Age
ref$ag.p50 <- ref$p50*ref$Age
ref$ag.p99 <- ref$p99*ref$Age
ref$ag.b30 <- ref$b30*ref$Age
ref$ag.b95 <- ref$b95*ref$Age
ref$ag.c02 <- ref$c02*ref$Age
ref$ag.c06 <- ref$c06*ref$Age
ref$ag.NZ_Site <- ref$NZ_Site*ref$Age
ref$ag.std.cr.width <- ref$std.cr.width*ref$Age
ref$ag.min.Ht.cr.base <- ref$min.Ht.cr.base*ref$Age
ref$ag.mean.chm.ht <- ref$mean.chm.ht*ref$Age
ref$ag.var.chm.ht <- ref$var.chm.ht*ref$Age
ref$ag.min <- ref$min*ref$Age
ref$ag.std <- ref$std*ref$Age
ref$ag.p10 <- ref$p10*ref$Age
ref$ag.p70 <- ref$p70*ref$Age
ref$ag.b05 <- ref$b05*ref$Age
ref$ag.b50 <- ref$b50*ref$Age
ref$ag.b99 <- ref$b99*ref$Age
ref$ag.c03 <- ref$c03*ref$Age
ref$ag.c07 <- ref$c07*ref$Age
ref$ag.Avg_Elev <- ref$Avg_Elev*ref$Age
ref$ag.p.count <- ref$p.count*ref$Age
ref$ag.min.cr.width <- ref$min.cr.width*ref$Age
ref$ag.max.Ht.cr.base <- ref$max.Ht.cr.base*ref$Age
ref$ag.min.chm.ht <- ref$min.chm.ht*ref$Age
ref$ag.p.stocking <- ref$p.stocking*ref$Age
ref$ag.max <- ref$max*ref$Age
ref$ag.ske <- ref$ske*ref$Age
ref$ag.p20 <- ref$p20*ref$Age
ref$ag.p90 <- ref$p90*ref$Age
ref$ag.b10 <- ref$b10*ref$Age
ref$ag.b70 <- ref$b70*ref$Age
ref$ag.c00 <- ref$c00*ref$Age
ref$ag.c04 <- ref$c04*ref$Age
ref$ag.cov <- ref$cov*ref$Age
ref$ag.Avg_Slp_De <- ref$Avg_Slp_De*ref$Age
ref$ag.mean.cr.width <- ref$mean.cr.width*ref$Age
ref$ag.max.cr.width <- ref$max.cr.width*ref$Age
ref$ag.std.Ht.cr.base <- ref$std.Ht.cr.base*ref$Age
ref$ag.max.chm.ht <- ref$max.chm.ht*ref$Age


#Squares
ref$avg.2 <- ref$avg^2
ref$kur.2 <- ref$kur^2
ref$p30.2 <- ref$p30^2
ref$p95.2 <- ref$p95^2
ref$b20.2 <- ref$b20^2
ref$b90.2 <- ref$b90^2
ref$c01.2 <- ref$c01^2
ref$c05.2 <- ref$c05^2
ref$dns.2 <- ref$dns^2
ref$Avg_Aspect.2 <- ref$Avg_Aspect^2
ref$var.cr.width.2 <- ref$var.cr.width^2
ref$mean.Ht.cr.base.2 <- ref$mean.Ht.cr.base^2
ref$var.Ht.cr.base.2 <- ref$var.Ht.cr.base^2
ref$std.chm.ht.2 <- ref$std.chm.ht^2
ref$Age.2 <- ref$Age^2
ref$qav.2 <- ref$qav^2
ref$p05.2 <- ref$p05^2
ref$p50.2 <- ref$p50^2
ref$p99.2 <- ref$p99^2
ref$b30.2 <- ref$b30^2
ref$b95.2 <- ref$b95^2
ref$c02.2 <- ref$c02^2
ref$c06.2 <- ref$c06^2
ref$NZ_Site.2 <- ref$NZ_Site^2
ref$std.cr.width.2 <- ref$std.cr.width^2
ref$min.Ht.cr.base.2 <- ref$min.Ht.cr.base^2
ref$mean.chm.ht.2 <- ref$mean.chm.ht^2
ref$var.chm.ht.2 <- ref$var.chm.ht^2
ref$min.2 <- ref$min^2
ref$std.2 <- ref$std^2
ref$p10.2 <- ref$p10^2
ref$p70.2 <- ref$p70^2
ref$b05.2 <- ref$b05^2
ref$b50.2 <- ref$b50^2
ref$b99.2 <- ref$b99^2
ref$c03.2 <- ref$c03^2
ref$c07.2 <- ref$c07^2
ref$Avg_Elev.2 <- ref$Avg_Elev^2
ref$p.count.2 <- ref$p.count^2
ref$min.cr.width.2 <- ref$min.cr.width^2
ref$max.Ht.cr.base.2 <- ref$max.Ht.cr.base^2
ref$min.chm.ht.2 <- ref$min.chm.ht^2
ref$p.stocking.2 <- ref$p.stocking^2
ref$max.2 <- ref$max^2
ref$ske.2 <- ref$ske^2
ref$p20.2 <- ref$p20^2
ref$p90.2 <- ref$p90^2
ref$b10.2 <- ref$b10^2
ref$b70.2 <- ref$b70^2
ref$c00.2 <- ref$c00^2
ref$c04.2 <- ref$c04^2
ref$cov.2 <- ref$cov^2
ref$Avg_Slp_De.2 <- ref$Avg_Slp_De^2
ref$mean.cr.width.2 <- ref$mean.cr.width^2
ref$max.cr.width.2 <- ref$max.cr.width^2
ref$std.Ht.cr.base.2 <- ref$std.Ht.cr.base^2
ref$max.chm.ht.2 <- ref$max.chm.ht^2


#sqrt
ref$avg.05 <- sqrt(abs(ref$avg))
ref$kur.05 <- sqrt(abs(ref$kur))
ref$p30.05 <- sqrt(abs(ref$p30))
ref$p95.05 <- sqrt(abs(ref$p95))
ref$b20.05 <- sqrt(abs(ref$b20))
ref$b90.05 <- sqrt(abs(ref$b90))
ref$c01.05 <- sqrt(abs(ref$c01))
ref$c05.05 <- sqrt(abs(ref$c05))
ref$dns.05 <- sqrt(abs(ref$dns))
ref$Avg_Aspect.05 <- sqrt(abs(ref$Avg_Aspect))
ref$var.cr.width.05 <- sqrt(abs(ref$var.cr.width))
ref$mean.Ht.cr.base.05 <- sqrt(abs(ref$mean.Ht.cr.base))
ref$var.Ht.cr.base.05 <- sqrt(abs(ref$var.Ht.cr.base))
ref$std.chm.ht.05 <- sqrt(abs(ref$std.chm.ht))
ref$Age.05 <- sqrt(abs(ref$Age))
ref$qav.05 <- sqrt(abs(ref$qav))
ref$p05.05 <- sqrt(abs(ref$p05))
ref$p50.05 <- sqrt(abs(ref$p50))
ref$p99.05 <- sqrt(abs(ref$p99))
ref$b30.05 <- sqrt(abs(ref$b30))
ref$b95.05 <- sqrt(abs(ref$b95))
ref$c02.05 <- sqrt(abs(ref$c02))
ref$c06.05 <- sqrt(abs(ref$c06))
ref$NZ_Site.05 <- sqrt(abs(ref$NZ_Site))
ref$std.cr.width.05 <- sqrt(abs(ref$std.cr.width))
ref$min.Ht.cr.base.05 <- sqrt(abs(ref$min.Ht.cr.base))
ref$mean.chm.ht.05 <- sqrt(abs(ref$mean.chm.ht))
ref$var.chm.ht.05 <- sqrt(abs(ref$var.chm.ht))
ref$min.05 <- sqrt(abs(ref$min))
ref$std.05 <- sqrt(abs(ref$std))
ref$p10.05 <- sqrt(abs(ref$p10))
ref$p70.05 <- sqrt(abs(ref$p70))
ref$b05.05 <- sqrt(abs(ref$b05))
ref$b50.05 <- sqrt(abs(ref$b50))
ref$b99.05 <- sqrt(abs(ref$b99))
ref$c03.05 <- sqrt(abs(ref$c03))
ref$c07.05 <- sqrt(abs(ref$c07))
ref$Avg_Elev.05 <- sqrt(abs(ref$Avg_Elev))
ref$p.count.05 <- sqrt(abs(ref$p.count))
ref$min.cr.width.05 <- sqrt(abs(ref$min.cr.width))
ref$max.Ht.cr.base.05 <- sqrt(abs(ref$max.Ht.cr.base))
ref$min.chm.ht.05 <- sqrt(abs(ref$min.chm.ht))
ref$p.stocking.05 <- sqrt(abs(ref$p.stocking))
ref$max.05 <- sqrt(abs(ref$max))
ref$ske.05 <- sqrt(abs(ref$ske))
ref$p20.05 <- sqrt(abs(ref$p20))
ref$p90.05 <- sqrt(abs(ref$p90))
ref$b10.05 <- sqrt(abs(ref$b10))
ref$b70.05 <- sqrt(abs(ref$b70))
ref$c00.05 <- sqrt(abs(ref$c00))
ref$c04.05 <- sqrt(abs(ref$c04))
ref$cov.05 <- sqrt(abs(ref$cov))
ref$Avg_Slp_De.05 <- sqrt(abs(ref$Avg_Slp_De))
ref$mean.cr.width.05 <- sqrt(abs(ref$mean.cr.width))
ref$max.cr.width.05 <- sqrt(abs(ref$max.cr.width))
ref$std.Ht.cr.base.05 <- sqrt(abs(ref$std.Ht.cr.base))
ref$max.chm.ht.05 <- sqrt(abs(ref$max.chm.ht))


#log
ref$logavg <- log(abs(ref$avg))
ref$logkur <- log(abs(ref$kur))
ref$logp30 <- log(abs(ref$p30))
ref$logp95 <- log(abs(ref$p95))
ref$logb20 <- log(abs(ref$b20))
ref$logb90 <- log(abs(ref$b90))
ref$logc01 <- log(abs(ref$c01))
ref$logc05 <- log(abs(ref$c05))
ref$logdns <- log(abs(ref$dns))
ref$logAvg_Aspect <- log(abs(ref$Avg_Aspect))
ref$logvar.cr.width <- log(abs(ref$var.cr.width))
ref$logmean.Ht.cr.base <- log(abs(ref$mean.Ht.cr.base))
ref$logvar.Ht.cr.base <- log(abs(ref$var.Ht.cr.base))
ref$logstd.chm.ht <- log(abs(ref$std.chm.ht))
ref$logAge <- log(abs(ref$Age))
ref$logqav <- log(abs(ref$qav))
ref$logp05 <- log(abs(ref$p05))
ref$logp50 <- log(abs(ref$p50))
ref$logp99 <- log(abs(ref$p99))
ref$logb30 <- log(abs(ref$b30))
ref$logb95 <- log(abs(ref$b95))
ref$logc02 <- log(abs(ref$c02))
ref$logc06 <- log(abs(ref$c06))
ref$logNZ_Site <- log(abs(ref$NZ_Site))
ref$logstd.cr.width <- log(abs(ref$std.cr.width))
ref$logmin.Ht.cr.base <- log(abs(ref$min.Ht.cr.base))
ref$logmean.chm.ht <- log(abs(ref$mean.chm.ht))
ref$logvar.chm.ht <- log(abs(ref$var.chm.ht))
ref$logmin <- log(abs(ref$min))
ref$logstd <- log(abs(ref$std))
ref$logp10 <- log(abs(ref$p10))
ref$logp70 <- log(abs(ref$p70))
ref$logb05 <- log(abs(ref$b05))
ref$logb50 <- log(abs(ref$b50))
ref$logb99 <- log(abs(ref$b99))
ref$logc03 <- log(abs(ref$c03))
ref$logc07 <- log(abs(ref$c07))
ref$logAvg_Elev <- log(abs(ref$Avg_Elev))
ref$logp.count <- log(abs(ref$p.count))
ref$logmin.cr.width <- log(abs(ref$min.cr.width))
ref$logmax.Ht.cr.base <- log(abs(ref$max.Ht.cr.base))
ref$logmin.chm.ht <- log(abs(ref$min.chm.ht))
ref$logp.stocking <- log(abs(ref$p.stocking))
ref$logmax <- log(abs(ref$max))
ref$logske <- log(abs(ref$ske))
ref$logp20 <- log(abs(ref$p20))
ref$logp90 <- log(abs(ref$p90))
ref$logb10 <- log(abs(ref$b10))
ref$logb70 <- log(abs(ref$b70))
ref$logc00 <- log(abs(ref$c00))
ref$logc04 <- log(abs(ref$c04))
ref$logcov <- log(abs(ref$cov))
ref$logAvg_Slp_De <- log(abs(ref$Avg_Slp_De))
ref$logmean.cr.width <- log(abs(ref$mean.cr.width))
ref$logmax.cr.width <- log(abs(ref$max.cr.width))
ref$logstd.Ht.cr.base <- log(abs(ref$std.Ht.cr.base))
ref$logmax.chm.ht <- log(abs(ref$max.chm.ht))


#Get naming of x and Y to match
names(ref)[names(ref) == 'center_x'] <- 'x'
names(ref)[names(ref) == 'center_y'] <- 'y'